const properties = [
  {
    id: 1,
    type: "appartement",
    transaction: "achat",
    title: "Appartement T3 lumineux",
    location: "Lyon 6e",
    price: 320000,
    surface: 72,
    rooms: 3,
    bedrooms: 2,
    featured: true,
    emoji: "🏢"
  },
  {
    id: 2,
    type: "maison",
    transaction: "achat",
    title: "Maison avec jardin",
    location: "Villeurbanne",
    price: 485000,
    surface: 130,
    rooms: 5,
    bedrooms: 4,
    featured: true,
    emoji: "🏡"
  },
  {
    id: 3,
    type: "appartement",
    transaction: "location",
    title: "Studio meublé centre-ville",
    location: "Lyon 2e",
    price: 750,
    surface: 28,
    rooms: 1,
    bedrooms: 0,
    featured: true,
    emoji: "🏠"
  },
  {
    id: 4,
    type: "maison",
    transaction: "location",
    title: "Maison 4 pièces",
    location: "Bron",
    price: 1350,
    surface: 95,
    rooms: 4,
    bedrooms: 3,
    featured: false,
    emoji: "🏘️"
  },
  {
    id: 5,
    type: "terrain",
    transaction: "achat",
    title: "Terrain constructible",
    location: "Mions",
    price: 150000,
    surface: 600,
    rooms: null,
    bedrooms: null,
    featured: true,
    emoji: "🌿"
  },
  {
    id: 6,
    type: "commercial",
    transaction: "location",
    title: "Local commercial 80 m²",
    location: "Lyon 3e",
    price: 1800,
    surface: 80,
    rooms: null,
    bedrooms: null,
    featured: false,
    emoji: "🏪"
  },
  {
    id: 7,
    type: "appartement",
    transaction: "achat",
    title: "Penthouse vue panoramique",
    location: "Lyon 5e",
    price: 620000,
    surface: 105,
    rooms: 4,
    bedrooms: 3,
    featured: false,
    emoji: "🏙️"
  },
  {
    id: 8,
    type: "maison",
    transaction: "achat",
    title: "Villa contemporaine",
    location: "Écully",
    price: 850000,
    surface: 220,
    rooms: 7,
    bedrooms: 5,
    featured: false,
    emoji: "🏰"
  }
];
